const express = require('express')

const authController = require('../controllers/authController')
const adminContentController = require('../controllers/adminContentController')
const adminDataController = require('../controllers/adminDataController')
const applicationController = require('../controllers/applicationController')
const contentController = require('../controllers/contentController')
const dashboardController = require('../controllers/dashboardController')
const governmentOfficialController = require('../controllers/governmentOfficialController')
const newsAdminController = require('../controllers/newsAdminController')
const potentialAdminController = require('../controllers/potentialAdminController')
const rutilahuController = require('../controllers/rutilahuController')
const accountController = require('../controllers/accountController')
const submissionController = require('../controllers/submissionController')
const serviceController = require('../controllers/serviceController')
const { requireAuth, requireSuperAdmin } = require('../middleware/auth')
const { applicationUpload, newsImageUpload, siteImageUpload, rutilahuSubmissionUpload, excelUpload } = require('../middleware/upload')
const asyncHandler = require('../utils/asyncHandler')
const { sendSuccess } = require('../utils/apiResponse')

const router = express.Router()

router.get('/health', (_req, res) => {
  return sendSuccess(res, {
    message: 'API Profil Kelurahan Kebon Lega aktif',
    data: { status: 'ok' },
  })
})

router.get('/profile', asyncHandler(contentController.getProfile))
router.get('/demographics', asyncHandler(contentController.getDemographics))
router.get('/officials', asyncHandler(governmentOfficialController.getPublic))
router.get('/news', asyncHandler(contentController.getNews))
router.get('/news/:id', asyncHandler(contentController.getNewsDetail))
router.get('/facilities', asyncHandler(contentController.getFacilities))
router.get('/potentials', asyncHandler(contentController.getPotentials))
router.get('/map/geojson', asyncHandler(contentController.getMapGeoJson))
router.get('/rutilahu', asyncHandler(rutilahuController.getPublicList))
router.get('/rutilahu/geojson', asyncHandler(rutilahuController.getGeoJson))
router.get('/rutilahu/:id/photo', asyncHandler(rutilahuController.getPhoto))
router.post('/rutilahu/track', asyncHandler(rutilahuController.track))
router.get('/services', asyncHandler(serviceController.getPublicServices))
router.post('/services/:id/applications', applicationUpload.any(), asyncHandler(applicationController.submitApplication))
router.post('/applications/track', asyncHandler(applicationController.trackApplication))

router.post('/contact', asyncHandler(submissionController.submitContact))
router.post('/guestbook', asyncHandler(submissionController.submitGuestbook))

router.post('/auth/login', asyncHandler(authController.login))
router.get('/auth/me', requireAuth, authController.me)
router.post('/auth/logout', authController.logout)

router.use('/admin', requireAuth, (req, _res, next) => {
  if (req.admin.role === 'rw' && !req.path.startsWith('/rutilahu') && req.path !== '/dashboard') {
    const AppError = require('../utils/AppError')
    return next(new AppError('Akun RW hanya dapat mengakses pengajuan RUTILAHU miliknya', 403))
  }
  return next()
})
router.get('/admin/dashboard', requireAuth, asyncHandler(dashboardController.getDashboard))
router.get('/admin/accounts/rw', requireSuperAdmin, asyncHandler(accountController.list))
router.post('/admin/accounts/rw', requireSuperAdmin, asyncHandler(accountController.create))
router.put('/admin/accounts/rw/:id', requireSuperAdmin, asyncHandler(accountController.update))
router.get('/admin/rutilahu', requireAuth, asyncHandler(rutilahuController.getAdminList))
router.get('/admin/rutilahu/export.xlsx', requireAuth, asyncHandler(rutilahuController.exportExcel))
router.get('/admin/rutilahu/template.xlsx', requireAuth, asyncHandler(rutilahuController.downloadTemplate))
router.post('/admin/rutilahu/import', requireAuth, excelUpload.single('file'), asyncHandler(rutilahuController.importExcel))
router.get('/admin/rutilahu/:id', requireAuth, asyncHandler(rutilahuController.getDetail))
router.post('/admin/rutilahu', requireAuth, rutilahuSubmissionUpload.fields([{ name: 'photo', maxCount: 1 }, { name: 'identity', maxCount: 1 }, { name: 'referral', maxCount: 1 }, { name: 'ownership', maxCount: 1 }]), asyncHandler(rutilahuController.create))
router.put('/admin/rutilahu/:id', requireAuth, rutilahuSubmissionUpload.fields([{ name: 'photo', maxCount: 1 }]), asyncHandler(rutilahuController.update))
router.delete('/admin/rutilahu/:id', requireAuth, asyncHandler(rutilahuController.remove))
router.get('/admin/rutilahu/:id/photo', requireAuth, asyncHandler(rutilahuController.getPhoto))
router.get('/admin/rutilahu/:id/documents/:kind', requireAuth, asyncHandler(rutilahuController.getDocument))
router.put('/admin/profile', requireAuth, siteImageUpload.fields([{name:'home_hero_image',maxCount:1},{name:'lurah_photo',maxCount:1},{name:'login_background_image',maxCount:1},{name:'government_hero_image',maxCount:1},{name:'potential_hero_image',maxCount:1},{name:'profile_map_image',maxCount:1}]), asyncHandler(adminContentController.updateProfile))
router.put('/admin/demographics', requireAuth, asyncHandler(adminContentController.updateDemographics))
router.get('/admin/officials', requireAuth, asyncHandler(governmentOfficialController.getAll))
router.post('/admin/officials', requireAuth, siteImageUpload.single('photo'), asyncHandler(governmentOfficialController.create))
router.put('/admin/officials/:id', requireAuth, siteImageUpload.single('photo'), asyncHandler(governmentOfficialController.update))
router.patch('/admin/officials/:id/position', requireAuth, asyncHandler(governmentOfficialController.updatePosition))
router.delete('/admin/officials/:id', requireAuth, asyncHandler(governmentOfficialController.remove))
router.post('/admin/demographics/areas', requireAuth, asyncHandler(adminContentController.createArea))
router.put('/admin/demographics/areas/:id', requireAuth, asyncHandler(adminContentController.updateArea))
router.delete('/admin/demographics/areas/:id', requireAuth, asyncHandler(adminContentController.deleteArea))
router.get('/admin/services', requireAuth, asyncHandler(serviceController.getAdminServices))
router.post('/admin/services', requireAuth, asyncHandler(serviceController.createService))
router.get('/admin/services/:id', requireAuth, asyncHandler(serviceController.getService))
router.put('/admin/services/:id', requireAuth, asyncHandler(serviceController.updateService))
router.delete('/admin/services/:id', requireAuth, asyncHandler(serviceController.deleteService))
router.get('/admin/news', requireAuth, asyncHandler(newsAdminController.getAll))
router.get('/admin/news/:id', requireAuth, asyncHandler(newsAdminController.getOne))
router.post('/admin/news', requireAuth, newsImageUpload.single('image'), asyncHandler(newsAdminController.create))
router.put('/admin/news/:id', requireAuth, newsImageUpload.single('image'), asyncHandler(newsAdminController.update))
router.delete('/admin/news/:id', requireAuth, asyncHandler(newsAdminController.remove))
router.get('/admin/potentials', requireAuth, asyncHandler(potentialAdminController.getAll))
router.post('/admin/potentials', requireAuth, siteImageUpload.single('image'), asyncHandler(potentialAdminController.create))
router.put('/admin/potentials/:id', requireAuth, siteImageUpload.single('image'), asyncHandler(potentialAdminController.update))
router.delete('/admin/potentials/:id', requireAuth, asyncHandler(potentialAdminController.remove))
router.get('/admin/applications', requireAuth, asyncHandler(applicationController.getApplications))
router.get('/admin/applications/:id', requireAuth, asyncHandler(applicationController.getApplication))
router.patch('/admin/applications/:id/status', requireAuth, asyncHandler(applicationController.updateApplicationStatus))
router.get('/admin/application-files/:id', requireAuth, asyncHandler(applicationController.downloadApplicationFile))
router.get('/admin/guestbook', requireAuth, asyncHandler(adminDataController.getGuestbook))
router.patch('/admin/guestbook/:id/status', requireAuth, asyncHandler(adminDataController.updateGuestbookStatus))
router.delete('/admin/guestbook/:id', requireAuth, asyncHandler(adminDataController.deleteGuestbook))
router.get('/admin/contacts', requireAuth, asyncHandler(adminDataController.getContacts))
router.patch('/admin/contacts/:id/status', requireAuth, asyncHandler(adminDataController.updateContactStatus))
router.delete('/admin/contacts/:id', requireAuth, asyncHandler(adminDataController.deleteContact))
router.get('/admin/export.xlsx', requireAuth, asyncHandler(adminDataController.exportExcel))

module.exports = router
