import { useState } from "react";
import { ArrowLeft, Clock3, LoaderCircle, Search } from "lucide-react";
import { Link } from "react-router-dom";
import Brand from "@/components/VillageBrand";
const API = import.meta.env.VITE_API_URL || "http://localhost:5000/api";
const label=value=>String(value||"").replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
export default function TrackRutilahu(){
 const [result,setResult]=useState(null),[error,setError]=useState(""),[loading,setLoading]=useState(false);
 async function submit(e){e.preventDefault();setLoading(true);setError("");setResult(null);try{const r=await fetch(`${API}/rutilahu/track`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(e.currentTarget)))}),b=await r.json();if(!r.ok)throw new Error(b.message);setResult(b.data)}catch(err){setError(err.message)}finally{setLoading(false)}}
 return <main className="min-h-screen bg-sage-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-5xl items-center justify-between px-5 py-4"><Brand/><Link to="/webgis-rutilahu" className="flex items-center gap-2 text-sm font-semibold"><ArrowLeft size={16}/> Peta RUTILAHU</Link></div></header><section className="mx-auto grid max-w-5xl gap-8 px-5 py-16 md:grid-cols-2"><div><p className="text-xs font-bold uppercase tracking-widest text-earth-500">Pelacakan publik</p><h1 className="mt-3 font-serif text-4xl text-forest-950">Cek status pengajuan RUTILAHU</h1><p className="mt-5 leading-7 text-stone-600">Masukkan kode pengajuan dan nomor kontak yang digunakan oleh pengaju. Identitas dan dokumen rumah tetap privat.</p></div><div className="rounded-2xl border border-sage-200 bg-white p-6 shadow-sm"><form onSubmit={submit} className="space-y-4"><label className="block text-sm font-bold">Kode pengajuan<input name="record_code" required placeholder="KBL-03-..." className="mt-1 w-full rounded-xl border px-4 py-3 font-mono"/></label><label className="block text-sm font-bold">Nomor kontak pengaju<input name="applicant_phone" required placeholder="08xxxxxxxxxx" className="mt-1 w-full rounded-xl border px-4 py-3"/></label><button disabled={loading} className="flex w-full justify-center gap-2 rounded-xl bg-forest-900 py-3 font-bold text-white">{loading?<LoaderCircle className="animate-spin"/>:<Search/>} Cek status</button></form>{error&&<p className="mt-4 rounded-xl bg-red-50 p-3 text-sm text-red-700">{error}</p>}{result&&<div className="mt-6 border-t pt-5"><h2 className="font-bold text-forest-950">{result.record_code}</h2><p className="mt-2 text-sm">Kategori: <b>{label(result.category)}</b></p><p className="text-sm">Verifikasi: <b>{label(result.verification_status)}</b></p><p className="text-sm">Penanganan: <b>{label(result.handling_status)}</b></p><div className="mt-4 space-y-3">{result.history.map(h=><div key={h.id} className="rounded-xl bg-sage-50 p-3 text-sm"><p className="flex items-center gap-2 font-bold"><Clock3 size={15}/>{label(h.action)}</p><p className="mt-1 whitespace-pre-line text-stone-600">{h.note||"Tanpa catatan"}</p></div>)}</div></div>}</div></section></main>
}
